### PR TITLE
Updates for new App Version 1.10.0.2000

### PR DESCRIPTION
**Pull request by beaudeanadams**
- Updated Dockerfile to best practice
- Updated appversion to 1.10.0.2000
- Statically set NumberOfLitres to 100

### CODE REVIEW

**Comment by MattKobayashi** [comment]
They now allow up to 150L to be locked, so probably best to set `NumberOfLitres = int(150)`. Otherwise looks good.

**Comment by freyta** [comment]
Hey mate.

I didn't use this pull request because you have the wrong APP_VERSION, which should be `1.10.0.2044`, and the NumberOfLitres should be 150, as can be seen with this fuel lock
`{
  "Id": "xxxx",
  "Status": 0,
  "CouponCode": "xxxx",
  "FuelGradeModel": 56,
  "CentsPerLitre": 150.9,
  "TotalLitres": 150,
  "StoreId": "1007",
  "ExpiresAt": xxxx,
  "CreatedAt": xxxx
}`

More than happy to pull the Dockerfile though if you just submit that by itself?

**Comment by beaudeanadams** [comment]
No worries buddy. Yeah, I made that realization after I submitted it. I wasn't 100% sure on the exact payload so didn't want to change it. 

> More than happy to pull the Dockerfile though if you just submit that by itself?

Yeah definitely can do. If you want, we can talk privately about helping you setup CI/DI for Dockerhub pushes? :)

**Comment by beaudeanadams** [comment]
@freyta, new PR sent through :)

**Pull request closed without merging**
