### PR TITLE
move API_KEY management to settings.py and allow OS environment variables to override it

### PR DESCRIPTION
**Pull request by drushbrook**
Hey @freyta,

Thought it may be easier to externalise the API_KEY variable outside app.py so we don't have to always change the variable when receiving updates or you don't need to change it to changethis when committing.

Stole the idea to use dotenv from @cliveli

### CODE REVIEW

**Comment by freyta** [comment]
Hey.
I like the idea, is there a reason we can't just make a new file called settings.py and then just import it all from there? Like this:
```
FROM settings IMPORT API_KEY, BASE_URL, PRICE_URL

def cheapestFuelAll():
    r = requests.get(PRICE_URL)
    *rest of code*
```

**Comment by cliveli** [comment]
Agree that will be better to have such variables in a central setting file. 

The reasons read the value from the OS env: 
1. able to dockerise the app. 
2. not introduce any conflict if upstream has any  updates

**Comment by drushbrook** [comment]
The benefit of dotenv is the ability to use both .env files and environment variables. The later allows us to create a public dockerized image without the need of a volume to override the settings file.

I guess we could achieve the same thing with the following and drop the dependency on the dotenv library

```
import settings

API_KEY = os.getenv('API_KEY',settings.API_KEY)
BASE_URL = os.getenv('BASE_URL',settings.BASE_URL)
PRICE_URL = os.getenv('PRICE_URL',settings.PRICE_URL)
```

Thoughts?

**Comment by freyta** [comment]
Sounds good to me. I've just merged the two

**Pull request merged**
